#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CFG_PATH="${OPENCLAW_CONFIG_PATH:-$HOME/.openclaw/openclaw.json}"
PUBLIC_URL="${OPENCLAW_PUBLIC_URL:-ws://127.0.0.1:18789}"
HOOK_TOKEN="${OPENCLAW_HOOKS_TOKEN:-}"
CRON_WEBHOOK_TOKEN="${OPENCLAW_CRON_WEBHOOK_TOKEN:-}"
OTEL_ENABLED_RAW="${OPENCLAW_OTEL_ENABLED:-false}"
OTEL_ENDPOINT="${OPENCLAW_OTEL_ENDPOINT:-}"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
BACKUP_PATH="${CFG_PATH}.ayex-feature-${STAMP}.bak"

if [[ ! -f "${CFG_PATH}" ]]; then
  echo "Hata: OpenClaw config bulunamadi: ${CFG_PATH}"
  echo "Once OpenClaw'i bir kez calistirip ~/.openclaw/openclaw.json olustur."
  exit 1
fi

export CFG_PATH PUBLIC_URL HOOK_TOKEN CRON_WEBHOOK_TOKEN OTEL_ENABLED_RAW OTEL_ENDPOINT BACKUP_PATH

python3 - <<'PY'
import json
import os
import secrets
from datetime import datetime, timezone
from pathlib import Path


def as_bool(value: str, default: bool = False) -> bool:
    normalized = (value or "").strip().lower()
    if not normalized:
        return default
    return normalized in {"1", "true", "yes", "on"}


cfg_path = Path(os.environ["CFG_PATH"])
public_url = os.environ["PUBLIC_URL"].strip() or "ws://127.0.0.1:18789"
hooks_token_env = os.environ["HOOK_TOKEN"].strip()
cron_token_env = os.environ["CRON_WEBHOOK_TOKEN"].strip()
otel_enabled = as_bool(os.environ.get("OTEL_ENABLED_RAW", "false"), default=False)
otel_endpoint = os.environ.get("OTEL_ENDPOINT", "").strip()

backup_path = Path(os.environ["BACKUP_PATH"])
backup_path.write_text(cfg_path.read_text(encoding="utf-8"), encoding="utf-8")

cfg = json.loads(cfg_path.read_text(encoding="utf-8"))

plugins = cfg.setdefault("plugins", {})
entries = plugins.setdefault("entries", {})
slots = plugins.setdefault("slots", {})

# Cleanup from older failed path escaping attempts.
entries.pop('"memory-lancedb"', None)

entries["memory-lancedb"] = {
    "enabled": True,
    "config": {
        "embedding": {
            "apiKey": "${OPENAI_API_KEY}",
            "model": "text-embedding-3-small",
        },
        "dbPath": str(Path.home() / ".openclaw" / "memory" / "lancedb"),
        "autoCapture": True,
        "autoRecall": True,
        "captureMaxChars": 650,
    },
}
slots["memory"] = "memory-lancedb"

entries["talk-voice"] = {"enabled": True}
entries["voice-call"] = {
    "enabled": True,
    "config": {
        "enabled": True,
        "provider": "mock",
        "outbound": {"defaultMode": "notify"},
        "inboundPolicy": "allowlist",
        "allowFrom": [],
        "serve": {"port": 3334, "bind": "127.0.0.1", "path": "/voice/webhook"},
        "store": str(Path.home() / ".openclaw" / "voice-call" / "calls.json"),
    },
}
entries["device-pair"] = {"enabled": True, "config": {"publicUrl": public_url}}
entries["diagnostics-otel"] = {"enabled": True}

diagnostics = cfg.setdefault("diagnostics", {})
diagnostics["enabled"] = True
otel = diagnostics.setdefault("otel", {})
otel["enabled"] = otel_enabled
otel["protocol"] = "http/protobuf"
otel["serviceName"] = "ayex-openclaw-local"
otel["traces"] = True
otel["metrics"] = True
otel["logs"] = False
otel["sampleRate"] = 0.25
otel["flushIntervalMs"] = 60000
if otel_endpoint:
    otel["endpoint"] = otel_endpoint
else:
    otel.pop("endpoint", None)

cron = cfg.setdefault("cron", {})
cron["enabled"] = True
cron["maxConcurrentRuns"] = 2
cron["webhookToken"] = cron_token_env or cron.get("webhookToken") or secrets.token_hex(24)
cron["sessionRetention"] = "24h"
run_log = cron.setdefault("runLog", {})
run_log["maxBytes"] = "2mb"
run_log["keepLines"] = 2000

hooks = cfg.setdefault("hooks", {})
hooks["enabled"] = True
hooks["token"] = hooks_token_env or hooks.get("token") or secrets.token_hex(24)
hooks["path"] = "/hooks"
hooks["maxBodyBytes"] = 262144
hooks["defaultSessionKey"] = "hook:ingress"
hooks["allowRequestSessionKey"] = False
hooks["allowedSessionKeyPrefixes"] = ["hook:"]
hooks["allowedAgentIds"] = ["main"]

cfg_path.write_text(json.dumps(cfg, ensure_ascii=True, indent=2) + "\n", encoding="utf-8")
os.chmod(cfg_path, 0o600)

tokens_path = Path.home() / ".openclaw" / "ayex-integration.tokens"
tokens_path.write_text(
    "# Generated by setup_openclaw_features.sh\n"
    f"OPENCLAW_HOOKS_TOKEN={hooks['token']}\n"
    f"OPENCLAW_CRON_WEBHOOK_TOKEN={cron['webhookToken']}\n",
    encoding="utf-8",
)
os.chmod(tokens_path, 0o600)

print("backup:", backup_path)
print("tokens:", tokens_path)
print("memory_slot:", slots.get("memory"))
print("otel_enabled:", otel_enabled)
PY

if [[ -f "${ROOT_DIR}/openclaw/openclaw.mjs" ]]; then
  if node "${ROOT_DIR}/openclaw/openclaw.mjs" config validate; then
    echo "OpenClaw config dogrulandi."
  else
    cp "${BACKUP_PATH}" "${CFG_PATH}"
    echo "Hata: config validate basarisiz. Guvenli geri alma yapildi: ${BACKUP_PATH}"
    exit 1
  fi
else
  echo "Uyari: ${ROOT_DIR}/openclaw/openclaw.mjs bulunamadi, validate atlandi."
fi

echo "Tamamlandi. Degisikliklerin etkili olmasi icin OpenClaw gateway'i yeniden baslat."
