#!/usr/bin/env bash
set -euo pipefail

BASE_URL="${BASE_URL:-http://127.0.0.1:8000}"
AYEX_USER="${AYEX_USER:-}"
AYEX_PASS="${AYEX_PASS:-}"

if [[ -z "${AYEX_USER}" || -z "${AYEX_PASS}" ]]; then
  echo "FAIL login missing AYEX_USER or AYEX_PASS env"
  exit 1
fi

FAILED=0

call_json_endpoint() {
  local name="$1"
  local method="$2"
  local path="$3"
  local payload="${4:-}"
  local use_auth="${5:-false}"
  local response_file
  response_file="$(mktemp)"

  local -a curl_args
  curl_args=(-sS -o "${response_file}" -w "%{http_code}" -X "${method}" "${BASE_URL}${path}")

  if [[ "${use_auth}" == "true" ]]; then
    curl_args+=(-H "Authorization: Bearer ${TOKEN}")
  fi

  if [[ "${method}" == "POST" || "${method}" == "PATCH" || "${method}" == "PUT" ]]; then
    curl_args+=(-H "Content-Type: application/json" -d "${payload}")
  fi

  local status
  status="$(curl "${curl_args[@]}")"
  if [[ "${status}" == "200" || "${status}" == "201" ]]; then
    echo "PASS ${name} status=${status}"
  else
    echo "FAIL ${name} status=${status} body=$(cat "${response_file}")"
    FAILED=1
  fi
  rm -f "${response_file}"
}

echo "[smoke] login"
login_response_file="$(mktemp)"
login_status="$(
  curl -sS -o "${login_response_file}" -w "%{http_code}" -X POST "${BASE_URL}/auth/login" \
    -H "Content-Type: application/json" \
    -d "{\"username\":\"${AYEX_USER}\",\"password\":\"${AYEX_PASS}\"}"
)"
if [[ "${login_status}" != "200" && "${login_status}" != "201" ]]; then
  echo "FAIL login status=${login_status} body=$(cat "${login_response_file}")"
  rm -f "${login_response_file}"
  exit 1
fi
TOKEN="$(
  python3 -c 'import json,sys; print((json.load(open(sys.argv[1])).get("access_token") or "").strip())' \
    "${login_response_file}"
)"
rm -f "${login_response_file}"
if [[ -z "${TOKEN}" ]]; then
  echo "FAIL login token_missing"
  exit 1
fi
echo "PASS login status=${login_status}"

echo "[smoke] health"
call_json_endpoint "health" "GET" "/health" "" "false"

echo "[smoke] chat (brief+market intent)"
call_json_endpoint \
  "chat" \
  "POST" \
  "/chat" \
  '{"text":"kısa anlat bugün piyasada ne oldu"}' \
  "true"

echo "[smoke] action (agent_task intent)"
call_json_endpoint \
  "action" \
  "POST" \
  "/action" \
  '{"text":"bitcoin ve ethereumu karşılaştır, kısa rapor hazırla"}' \
  "true"

echo "[smoke] event ingest"
call_json_endpoint \
  "events_ingest" \
  "POST" \
  "/events/ingest" \
  '{"title":"Smoke Test Event","summary":"This is a smoke test event generated by the test script to verify ingest pipeline is working correctly","category":"tech","importance":5,"tags":["smoke-test"]}' \
  "true"

echo "[smoke] sessions"
call_json_endpoint "sessions" "GET" "/sessions" "" "true"

echo "[smoke] intel"
call_json_endpoint "intel" "GET" "/intel" "" "true"

echo "[smoke] done"
if [[ "${FAILED}" -ne 0 ]]; then
  exit 1
fi
